name: Update Release

on:
  workflow_dispatch:  # 手动触发事件
  schedule:
    - cron: '0 0 * * *'  # 每天触发一次，你也可以根据需要调整定时规则

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: do
      id: get_release
      run: |
        VERSION=$(curl -s https://api.github.com/repos/fluid-dev/hexo-theme-fluid/releases/latest | jq -r '.tag_name')
        VERSION_NUMBER=$(echo $VERSION | grep -oE '[0-9.]+')
        LOCAL_VERSION=$(cat version)
        if [ "$LOCAL_VERSION" != "${VERSION}" ]; then
          echo "Versions are different. Updating..."
          mkdir update_tmp
          cd update_tmp
          curl -LJO "https://github.com/fluid-dev/hexo-theme-fluid/archive/refs/tags/${VERSION}.tar.gz"
          tar -xzf "hexo-theme-fluid-${VERSION_NUMBER}.tar.gz"
          cd "hexo-theme-fluid-${VERSION_NUMBER}"
          cp -r ../../scripts ../../source .
          zip -r ../../update.zip .
          echo "success"
        else
          echo "Versions are the same. No update needed."
        fi

    - name: Deploy update
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        commit_message: Update app
        build_dir: ./version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
