name: Update Release

on:
  workflow_dispatch:
  schedule:
    - cron: '7 7 * * *'

jobs:
  update-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: do
      id: get_release
      run: |
        VERSION=$(curl -s https://api.github.com/repos/fluid-dev/hexo-theme-fluid/releases/latest | jq -r '.tag_name')
        VERSION_NUMBER=$(echo $VERSION | grep -oE '[0-9.]+')
        LOCAL_VERSION=$(cat version)
        if [ "$LOCAL_VERSION" != "${VERSION}" ]; then
          echo "Versions are different. Updating..."
          mkdir update_tmp
          cd update_tmp
          curl -LJO "https://github.com/fluid-dev/hexo-theme-fluid/archive/refs/tags/${VERSION}.tar.gz"
          tar -xzf "hexo-theme-fluid-${VERSION_NUMBER}.tar.gz"
          cd "hexo-theme-fluid-${VERSION_NUMBER}"
          cp -r ../../scripts ../../source .
          mkdir ../../release
          zip -r "../../release/hexo-theme-fluid-${VERSION_NUMBER}.zip" .
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          cd ..
          cd ..
          echo ${VERSION} > version
          git add version
          git commit -m "update"
          git push
          echo "VERSION_TAG=${VERSION}" >> $GITHUB_ENV
        else
          echo "Versions are the same. No update needed."
          exit 0
        fi
        
    - name: release
      if: env.VERSION_TAG
      uses: ncipollo/release-action@v1
      with:
          artifacts: "./release/*"
          allowUpdates: true
          tag: ${{ env.VERSION_TAG }}
