name: Update Release

on:
  workflow_dispatch:  # 手动触发事件
  schedule:
    - cron: '0 0 * * *'  # 每天触发一次，你也可以根据需要调整定时规则

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release version
      id: get_release
      run: |
        VERSION=$(curl -s https://api.github.com/repos/fluid-dev/hexo-theme-fluid/releases/latest | jq -r '.tag_name')
        echo "Latest release version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Compare versions
      id: compare_versions
      run: |
        LOCAL_VERSION=$(cat version)
        if [ "$LOCAL_VERSION" != "${{ steps.get_release.outputs.version }}" ]; then
          echo "Versions are different. Updating..."
          VERSION=${{ steps.get_release.outputs.version }}
          echo "Using release version: $VERSION"
          mkdir update_tmp
          cd update_tmp
          curl -LJO https://github.com/fluid-dev/hexo-theme-fluid/archive/refs/tags/${VERSION}.tar.gz  # 修正链接
          tar -xzf ${VERSION}.tar.gz
          cp -r hexo-theme-fluid-${VERSION}/scripts hexo-theme-fluid-${VERSION}/source .
          zip -r update.zip .
          echo "::set-output name=update_path::$(pwd)/update.zip"
        else
          echo "Versions are the same. No update needed."
        fi

    - name: Create new release
      id: create_release
      if: steps.compare_versions.outputs.update_path || github.event_name == 'workflow_dispatch'
      run: |
        RELEASE_ID=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary "@${{ steps.compare_versions.outputs.update_path }}" \
          "https://api.github.com/repos/huaxianyan/custom_hexo_fluid/releases?tag_name=${{ steps.get_release.outputs.version }}&name=${{ steps.get_release.outputs.version }}&draft=false" \
          | jq -r '.id')
        echo "Created release with ID $RELEASE_ID"

    - name: Update local version file
      if: steps.compare_versions.outputs.update_path || github.event_name == 'workflow_dispatch'
      run: echo "${{ steps.get_release.outputs.version }}" > version
