name: Update Release

on:
  workflow_dispatch:  # 手动触发事件
  schedule:
    - cron: '0 0 * * *'  # 每天触发一次，你也可以根据需要调整定时规则

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release version
      id: get_release
      run: |
        VERSION=$(curl -s https://api.github.com/repos/fluid-dev/hexo-theme-fluid/releases/latest | jq -r '.tag_name')
        echo "Latest release version: $VERSION"
        VERSION_NUMBER=$(echo $VERSION | grep -oE '[0-9.]+')
        echo "::set-output name=version::$VERSION"

    - name: Compare versions
      id: compare_versions
      run: |
        echo $VERSION
        echo $VERSION_NUMBER


